### PR TITLE
.Net Core version of amazon-kinesis-client-net

### PR DESCRIPTION
**Pull request by khaledsobhy83**
#8 

.Net core version of amazon-kinesis-client-net. I had my chances and tried to port the library to .net core but found many challenges, the biggest was the .net core version of Stateless library (https://github.com/dotnet-state-machine/stateless/issues/223). They fixed the issue and released a new version that I am using here.

TODO

1. Since now this is a cross platform library, I commented the registry part for locating java because it is 
    windows specific and later will add something that can work on different operating systems.
2. The HelpOption attribute is removed from the latest ComandLineParser library and I did not get why do you need this attribute so I removed it and everything was still working just fine. I want to investigate on how to achieve the same functionality using the new library.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by khaledsobhy83** [comment]
@pfifer Hope you have sometime to look into this PR

**Comment by nickhetland** [comment]
This is a straight up conversion to .NET core. This removes support for the .NET Framework version, which I assume there might be a number of people that have dependencies that require the .NET Framework. (I am mostly interested in a .NET Core version)

One main change that I recommend is changing the _ClientLibrary_ project to have a targeted framework of _netstandard2.0_ instead of _netcoreapp2.0_.
The _SampleConsumer_ and _SampleProducer_ projects would have to be duplicated for a .NET Core and .NET Framework, but it might not be worth the duplication of code just to demonstrate that the library works for either runtimes.
One thing that I am not entirely sure is if a .NET Core version of the Bootstrap project will work with a .NET Framework version of the _SampleConsumer_ project. Maybe the MultiLangDaemon functionality handles it just fine.

**Comment by nickhetland** [comment]
I was able to validate that this pull requests works. One thing that I would like to highlight is that the _executableName_ property in the properties file needs to include the dotnet command in it. For example:

`executableName = dotnet SampleConsumer.dll`

The _SampleConsumer\kcl.properties_ file should be updated to reflect this change.

**Comment by pfifer** [comment]
Thanks for validating, that will help with testing.  I still have some internal processes that need to complete before I will be able to to merge.  It's unlikely that the merge will occur this week, but I will definitely try and get it done next week.

**Comment by khaledsobhy83** [comment]
I added "dotnet SampleConsumer.dll" to the kcl.properties as recommended by @nickhetland .

**Comment by pfifer** [comment]
@khaledsobhy83 can you please pull master into your branch?  Your branch appears out of date.

**Comment by khaledsobhy83** [comment]
@pfifer -----> done

**Pull request merged**
